flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- ALUT-2.4.0.2
- OpenAL-1.7.0.4
resolver: lts-7.2
# TODO: Get rid of this somehow...
# NOTE: The relative path issue may have been fixed
#       (cf. https://github.com/commercialhaskell/stack/issues/2830)
extra-lib-dirs:
- ./dependencies/freealut/admin/VisualStudio6/alut/x64/Release
- ./dependencies/openal-soft-1.16.0-bin/openal-soft-1.16.0-bin/libs/Win64
