flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- ALUT-2.4.0.2
- OpenAL-1.7.0.4
resolver: lts-7.2
include-dirs:
- C:/Users/Jonatan/Downloads/Programmering/freealut/include/AL
- C:/Users/Jonatan/Downloads/Programmering/openal-soft-1.16.0-bin/openal-soft-1.16.0-bin/include
- C:/Users/Jonatan/Downloads/Programmering/freetype-2.5.5-vc11-64/freetype-2.5.5-vc11-64/include
- C:/Users/Jonatan/Downloads/Programmering/ftgl-2.1.3-vc11-64/ftgl-2.1.3-vc11-64/include
extra-lib-dirs:
- C:/Users/Jonatan/Downloads/Programmering/freealut/admin/VisualStudio6/alut/x64/Release
- C:/Users/Jonatan/Downloads/Programmering/openal-soft-1.16.0-bin/openal-soft-1.16.0-bin/libs/Win64
- C:/Users/Jonatan/Downloads/Programmering/freetype-2.5.5-vc11-64/freetype-2.5.5-vc11-64/lib
- C:/Users/Jonatan/Downloads/Programmering/ftgl-2.1.3-vc11-64/ftgl-2.1.3-vc11-64/lib